name: Deploy to AWS

on:
  push:
    branches:
      - qa
      - main

jobs:
  deploy:
    name: Deploy to AWS Instances
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection to EC2_QA
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@34.207.159.80 "echo 'SSH connection successful'"

      - name: Deploy to QA
        if: github.ref == 'refs/heads/qa'
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@34.207.159.80 "sudo rm -rf /var/www/html/*"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa index.html ec2-user@34.207.159.80:/var/www/html/

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          for host in 34.204.95.178 54.198.183.180 44.200.53.237; do
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$host "sudo rm -rf /var/www/html/*"
            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa index.html ec2-user@$host:/var/www/html/
          done
